name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - run: bun install
      - run: bun run build
      
      # - uses: szenius/set-timezone@v1.2
      #   with:
      #     timezoneLinux: "Asia/Singapore"
      #     timezoneMacos: "Asia/Singapore"
      #     timezoneWindows: "Singapore Standard Time"

      - name: Test
        run: bun test
        env:
          TZ: "Asia/Shanghai"

      - name: Publish Dry Run
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
